# Generated by Django 4.1.7 on 2023-03-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infusion_analysts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth',
        ),
    ]
